#
# Nimbus
# K8s Deployment
# Monitoring
#

apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - namespace.yaml
  # NOTE: Prometheus Operator CRDs should be upgraded in tandem withn the kube-prometheus helm chart
  - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.60.1/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.60.1/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.60.1/example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.60.1/example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.60.1/example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.60.1/example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
  - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.60.1/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.60.1/example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
helmCharts:
  # Monitoring: Prometheus, Grafana & Prometheus Operator
  - namespace: monitoring
    releaseName: monitor
    name: kube-prometheus-stack
    version: 42.1.0
    repo: https://prometheus-community.github.io/helm-charts
    valuesInline:
      grafana:
        grafana.ini:
          paths:
            data: /var/lib/grafana/
            logs: /var/log/grafana
            plugins: /var/lib/grafana/plugins
            provisioning: /etc/grafana/provisioning
          log:
            mode: console
          # delegate authentication to proxy authentication proxy using headers forwarded by ingress
          auth.proxy:
            enabled: true
            header_name: X-Auth-Request-User
            header_property: username
            auto_sign_up: true
            headers: "Email:X-Auth-Request-Email"
        additionalDataSources:
          # add loki as a grafana datasource for logs
          - version: 1
            orgId: 1
            uid: loki
            name: loki
            access: proxy
            editable: false
            type: loki
            url: http://loki-gateway.monitoring.svc.cluster.local
  # Logging: Loki
  - namespace: monitoring
    releaseName: log
    name: loki
    version: 3.6.0
    repo: https://grafana.github.io/helm-charts
    valuesFile: ./loki-values.yaml
  # Log Forwarder: promtail
  - namespace: monitoring
    releaseName: logs
    name: promtail
    version: 6.7.2
    repo: https://grafana.github.io/helm-charts
    valuesInline:
      # monitor promtail's metrics with Prometheus
      serviceMonitor:
        enabled: true

# corce all resources to deploy in monitoring namespace
# needed as Loki's helm chart does not respect the namespace set at helmCharts level
namespace: monitoring
