#
# Nimbus
# K8s Deployment
# Monitoring
#

apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - https://github.com/prometheus-operator/prometheus-operator/releases/download/v0.65.1/bundle.yaml
helmCharts:
  # Monitoring: Prometheus, Grafana & Prometheus Operator
  - namespace: monitoring
    releaseName: monitor
    name: kube-prometheus-stack
    version: 45.27.2
    repo: https://prometheus-community.github.io/helm-charts
    valuesInline:
      grafana:
        grafana.ini:
          paths:
            data: /var/lib/grafana/
            logs: /var/log/grafana
            plugins: /var/lib/grafana/plugins
            provisioning: /etc/grafana/provisioning
          log:
            mode: console
          # delegate authentication to proxy authentication proxy using headers forwarded by ingress
          auth.proxy:
            enabled: true
            header_name: X-Auth-Request-User
            header_property: username
            auto_sign_up: true
            headers: "Email:X-Auth-Request-Email"
          users:
            # user authenticated by auth proxy are assigned 'Editor' role
            auto_assign_org_role: Editor
        additionalDataSources:
          # add loki as a grafana datasource for logs
          - version: 1
            orgId: 1
            uid: loki
            name: loki
            access: proxy
            editable: false
            type: loki
            url: http://loki-gateway.monitoring.svc.cluster.local
patches:
  # patch kube-promtheus-stack's Jobs with to ttl to be cleaned up once they finish executing
  - path: patch-job-ttl.yaml
    target:
      group: batch
      version: v1
      kind: Job
      labelSelector: "app.kubernetes.io/part-of=kube-prometheus-stack"
