#
# Nimbus
# Gitleaks config
#

# extend default config
[extend]
useDefault = true

[allowlist]
description = "global allow list"
# false positives in the dotenv template
regexes = [
  '''CLOUDFLARE_API_TOKEN=''',
  '''B2_APPLICATION_KEY_ID=''',
  '''B2_APPLICATION_KEY=''',
]
