repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-merge-conflict
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: mixed-line-ending
    args: ["-f", "lf"]

# check for secrets
- repo: https://github.com/zricethezav/gitleaks
  rev: v8.8.6
  hooks:
    - id: gitleaks-docker

# check for spelling mistakes
- repo: https://github.com/codespell-project/codespell
  rev: v2.1.0
  hooks:
  - id: codespell
    args: [-I, .codespellignore]

# lint github actions workflows
- repo: https://github.com/sirosen/check-jsonschema.git
  rev: 0.33.0
  hooks:
  - id: check-github-workflows

# lint terraform
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.72.1
  hooks:
  - id: terraform_fmt
    args:
      - --args=-recursive -no-color
  - id: terraform_validate
    args:
      - --args=-no-color

# lint dockerfiles
- repo: https://github.com/hadolint/hadolint
  rev: v2.10.0
  hooks:
    - id: hadolint-docker

# format python code
- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
  - id: black
