repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-merge-conflict
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace

# check for secrets
- repo: https://github.com/Yelp/detect-secrets
  rev: v1.1.0
  hooks:
  - id: detect-secrets
    args:
    - '--baseline'
    - '.secrets.baseline'

# check for spelling mistakes
- repo: https://github.com/codespell-project/codespell
  rev: v2.1.0
  hooks:
  - id: codespell

# lint github actions workflows
- repo: https://github.com/sirosen/check-jsonschema.git
  rev: 0.13.0
  hooks:
  - id: check-github-workflows

# lint terraform HCL formatting
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.72.1
  hooks:
  - id: terraform_fmt
    args:
      - --args=-recursive
