#
# Nimbus
# Authentication
# Kustomization
#

resources:
  - namespace.yaml
helmCharts:
  # Authentication: OAuth2 Proxy
  - name: oauth2-proxy
    version: 6.9.1
    repo: https://oauth2-proxy.github.io/manifests
    releaseName: login
    valuesInline:
      # expose oauth2 proxy via ingress
      ingress:
        enabled: true
        className: nginx
        pathType: Prefix
      # only allow users with specific emails to authenticate
      authenticatedEmailsFile:
        enabled: true

configMapGenerator:
  - name: login-oauth2-proxy
    behavior: merge
    files:
      - oauth2-proxy/oauth2_proxy.cfg
  - name: login-oauth2-proxy-accesslist
    files:
      - restricted_user_access=oauth2-proxy/authenticated_emails_file

secretGenerator:
  # patch oauth2 proxy secret with actual secret values
  - name: login-oauth2-proxy
    behavior: replace
    # unset env vars in env file will be read from the execution environment
    # https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/#configmapgenerator
    env: oauth2-proxy/secret.env
patches:
  - path: oauth2-proxy/patch-deployment.yaml
  - path: oauth2-proxy/patch-ingress.yaml

namespace: auth
commonLabels:
    app.kubernetes.io/part-of: auth
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kustomize
