#
# Nimbus
# Authentication
# Kustomization
#

resources:
  - namespace.yaml
  - ./oauth2-proxy
# merge & replace oauth2-proxy resources must done outside oauth2-proxy kustomize
configMapGenerator:
  - name: login-oauth2-proxy
    behavior: merge
    files:
      - oauth2-proxy/oauth2_proxy.cfg
secretGenerator:
  # patch oauth2 proxy secret with actual secret values
  - name: login-oauth2-proxy
    behavior: replace
    env: oauth2-proxy/secret.env
namespace: auth
commonLabels:
    app.kubernetes.io/part-of: auth
    app.kubernetes.io/created-by: kustomize
