#
# Nimbus
# Media Streaming Service
# Persistent Volume Patch
#

apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-data
spec:
  csi:
    volumeAttributes:
      remotePath: mrzzy-co-media/csi-fs
      # both jellyfin & rtorrent-flood pod's have a emptydir volume mounted at /cache
      cache-dir: /cache
      # enable full read / write vfs cache mode to cache rtorrent-flood's writes & jellyfin's reads
      vfs-cache-mode: full
      vfs-cache-max-size: 5G
      # vfs performance: disable modefile
      no-modtime: "true"
