#
# Nimbus
# K8s Deployment
# Media Streaming Service PVC
#

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-data
spec:
  # store media files in cheaper Backblaze B2 cloud object storage
  storageClassName: csi-s3
