#
# nimbus
# ingress-nginx kustomization
#

# deploy ingress nginx for ingress support
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.47.0/deploy/static/provider/cloud/deploy.yaml
patches:
# disable validating webhook due to issue with certificate issues with different
# conflicting ingress controllers: https://github.com/kubernetes/ingress-nginx/issues/6458
- patch: |-
    $patch: delete
    apiVersion: admissionregistration.k8s.io/v1
    kind: ValidatingWebhookConfiguration
    metadata:
      name: ingress-nginx-admission
