#
# Nimbus
# Media Streaming Server
# Media Files Volume Claim
#

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-data
spec:
  accessModes:
  - ReadWriteOnce
  # TODO(mrzzy): replace this with kustomize replacement
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      stores: media-data
