apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: elastic-creds
  namespace: logging
spec:
  encryptedData:
    FLUENT_ELASTICSEARCH_PASSWORD: AgBOOXbCx+ukwVj2d4dZgDPQVJtVcMN3qXtFGN5oI5vxUyI7xPB8St1Zj/kMvxN8HIAXw0TazYySAP737qrWVz87vpRCn3kpsKeglkoF+OHzB0JobzlJ64onMsobkPcHTqRwJcDQJoYsiKU2Ylq3Fku5D3DeGzsSOixeDJeDs/INeUzMD8JXWSacELFcpIxS8zL4VvEspgER1Qha2szZPjAK4ZJtSHeJ6IKgUCvkSBTOZ9ZQStxX2EBO0s7Wxzb+r5AFY5R5DA8PPGwOz5LdxfoQMD5GgYReDELIenDRRbJrVT2tuwvlVKVWK9cjp+/qwnnCd40XVzIVU795JBMObSrRoXhJw2/Io62031lgCcbjIGagyD5n5koH7mw8clRqJAlXJbJqqOhYpBRuVY2XZea7ODW9PYlJwwYrBdZJPVRjIzFYqgY8pECRKTulONDR5xrEwc8LjjAtwyagwg/wlV5dr3Ja7/f/rk5Mw74P0j/GHaEdM+xcaLM+jqR2cBOoxjUSATUWjl0gXQHONAvMg0nuqSx03htEuBidVRqmnJqK4XAHBDcHln2QKwBxmxLBu9UKgzTDilcAU+kfn3mJ0v0rbRCcByomZd+CIWtxKYRQ60m3D7bZ/vSppQJef2BEUDcnaShUsdtNXOk2G7x2seIzhAQVywTggECTF9FiSqZWakpOOu7y2xUHX5IxKqTnxAYdZv6cKEGpYmztUAuvsorSfeXGtfXIYQh3zg== # pragma: allowlist secret
    FLUENT_ELASTICSEARCH_USER: AgCrJ+YF7v+FUl/exmCIzYO4CeB2/jfdDcSrSNpEhqQyyGpSR9u9EPSpf58px1Qkd4TJIL6L1DgfpwQ4mwsJ8mF3+8jL7JKuoRJ1c7lH+ufZ9EUhGdA6foZwl+oTvqnTmruGV+44z7T+/WvpnA/8GfEnEGLlrKQWlH8LFlamrxhf7PchNTGrva24NaYpRLVazbwQiBzAT1SHa3bgPBVqOV04H3Od3bBVXAxOxcLAnQK6Pt6zjtvNSdT2d3zK4zflg7m/zAxQtHDjG8nNfab8j21SBLPXGiaPIzm9CN9X7x9QL7UxYMlCm2PdnMWY7MzzCeD9O0XSSL4Lx7aX2NKfh4VQwBs/Fn3K/mov/2d/9iCBUCUzpTWIVDYqrfJd6tPZT06jmT1GBje5bRZ7XXrVmPfen63Xyy3Ke5w4K3k8PBnWpP4Udu7jw3+3crVVx5HA9l+kwbVpdOdOtnB3MBU7MFZPZUAgWmxyE47M0Kx6MuxL5X1Rkx0ntjc/3XoU3MXOn1OPKxiDR8TqUWdRmldAZxjvwRrqMhRzWyfhBLjxXp1Fw10rJiEGBgQNQZlmP6X6XeMD36J1U/C6iZ/mouzgwC1/+QaUADNaG6TiL0l5A5npKRbOpbgta8hVsxM5+vHE2Ljg9w3OM1IKZfNq2L2i56p3vaIZ+3ZKKX56EFRzRVWdhY6WApFke1rtZT1PkUX9Fpc4T5e0G0Md9UGJT1yd # pragma: allowlist secret
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: elastic-creds
      namespace: logging
