#
# nimbus
# argocd app to deploy argo-workflows
#

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mrzzy/nimbus.git
    targetRevision: HEAD
    path: k8s/kustomize/argo-workflows
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
