#
# nimbus
# argocd app to deploy operator-lifecycle-manager
#

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operator-lifecycle-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mrzzy/nimbus.git
    targetRevision: HEAD
    path: k8s/kustomize/operator-lifecycle-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: olm
