#
# nimbus
# argocd app to deploy tiddlywiki
#

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tiddlywiki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mrzzy/nimbus.git
    targetRevision: HEAD
    path: k8s/kustomize/tiddlywiki
  destination:
    server: https://kubernetes.default.svc
    namespace: tiddlywiki
