#
# Nimbus
# K8s Deployment
# Monitoring
#

apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - namespace.yaml
  # Monitoring: Prometheus, Grafana & Prometheus Operator
  - kube-promtheus-stack
  - grafana-ingress.yaml
helmCharts:
  # Logging: Loki
  - namespace: monitoring
    releaseName: log
    name: loki
    version: 5.5.12
    repo: https://grafana.github.io/helm-charts
    valuesFile: ./loki-values.yaml
  # Log Forwarder: promtail
  - namespace: monitoring
    releaseName: logs
    name: promtail
    version: 6.11.2
    repo: https://grafana.github.io/helm-charts
    valuesInline:
      # monitor promtail's metrics with Prometheus
      serviceMonitor:
        enabled: true
# corce all resources to deploy in monitoring namespace
# needed as Loki's helm chart does not respect the namespace set at helmCharts level
namespace: monitoring
