#
# admin
# do k8s sg cluster definitions
# tiddlywiki
#

apiVersion: v1
kind: Service
metadata:
  name: tiddlywiki
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
