#
# nimbus
# keycloak client
# used by oauth-proxy to provide authentication for tiddlywiki
#

apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: tiddlywiki-oauth
  labels:
spec:
  realmSelector:
     matchLabels:
      app: tiddlywiki
      deployed-for: tiddlywiki
  client:
    # name of the client
    clientId: tiddlywiki-oauth-client
    # suffix of the secret that stores the oauth2 client credentials
    # actual secret name is prefixed with 'keycloak-client-secret'
    secret: tiddlywiki-oauth # pragma: allowlist secret
    # enable standard oauth2 flow
    standardFlowEnabled: true
    # valid urls to redirect oauth authorization codes to
    redirectUris:
      - "https://wiki.mrzzy.co/oauth2/callback"
