apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wg-config-secret
  namespace: wireguard
spec:
  encryptedData:
    wg0.conf: AgAdRbSF5BNCFt4yEBB4Gis5nUXcvV9XZwdcOtn7wckYIAIMT0nqP5YikMUDJpaY2WG+6OYZJJl03bfBrCZaYRn7f/Wzzxrasl2X5PZGidxk7HX41pJsFnn2Ld9q0iUMGS9JOQ5V9U8+BQF45XvLjfJoB8ue/qujnqCOA3q3UacGJPuVl4TvIEWZgaB/tavtIC8OoeyTZpU9ihzg+BAgZ+p6yKAbBtw43uy7fSTdFQ7jcIuVeQ1mxU/H3Be0MRKQjYahSydcMLVq2VHm49nIgsmiFNj3mYzmRfA83aQNTLCowJP+vvj2x/fkPImydpVsjvvN3w4xnSEnD89d/3kZKDSTNNBWRZ4i89N1ii2/ioR+JKhIE0L5S8Ff9ceGVSil5xI2GCm+lSMHN4PemEwFORhA1Kt+6zxJTft/t9v075KHVML6LzJY1qHMPCx4aBO+0uoG7I6R6Hjlze/ieGfhjTJbTW50zHX0VTp0wKs2K/jSgHNVAAP9rRyjsAkth4oExdF6HR41um0wXvRWKuFK9OUHgKUYVoJTvqAWYLeUCQRd3x6E8kJ63uURgffVAOwlHnwEbphqknWCQLg4pC4KO4dE2NCrxQRycr7zvF6+1XLW5pgSAnMR4wbtNyA2j3rkiWNaP5asBbugDVEDn4aDtAM48Oq7RPQ1PrLY1k7aqOG0hairL6ylDo+gjFknt5hWidkEEpV1+u4kx7W2YUkA33Gx/ULaNvNmeJLUxhsA6oWJto888P+iM3VHTVeWYLFJ+kQ1UY9ASZzgXvYslmYjwR3LT8hVWuWOusAyyWCPqIBQrqEvDEzTVfRTkYROEdZY2CtZR1apUFVj3H6V4+aeqX5vLaREiCyVrrsrwWXO1hvkLqPbXfGWkYsOvSNrfa0Z3pF6NiogSyfFfNIcoIl6BeGLDXZGGn7CKYSS3kILI/NBGEYIY56dklpBSff5fLxficRJrdwE4Oc1dKeWzAtiHTaE4LzzxEZWVkbDd5b3L9sUydhGx1u9SSz/GEGEDxB2bqW8xa7Ab2VredlDQENL0WLzFLjONryYgVyptHk825jx9f+yLc7d3it+YdnpP9P58J7uqjUbc6qmPFSYXR3qM1B1rLQziumoJ4tOPvfh0SK2Yjccht1p4E/jSmJgyUQh8Ou/FlvMYJ+aV7wrK1bcCrWVosxMoxHTBIa8IvaxtR8JK/FnhXgqp79qKQMipCfoOqAzzl5YUD1UKFcxggHc9+TJ/0PRor9R2qe9RlhVRc3sEOkxr81/Atdw9H+n9ca8HIdt6MNXqTxfvd7JGtzbf0cBORdlde1e6YERFsewI6niwSVziZ7noOgA9QyOOqZg1sSbGJ83t2bPUCW8qsOzJAgX33uS96S/NqUx0NqPIdKRrMP3nfXf4lWiBZdw3otlETT7Z7rnjUVbqKFOZCvk5RozgTOujzfYQImzrzilf/ZmR8oXch2hIqB7Ww9HuxODUVm0OidlcHjCBn5yEivs1yd6+3OHSLQnd28f7QMRxuI3RIs90l0a8CSO8LDDC2Hynh6L0MyDVihTntaYZsa+Pyr+Nq8QNmqvP/JU32O9T+JczQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: wg-config-secret
      namespace: wireguard

