#
# admin
# do k8s sg cluster definitions
# wireguard vpn
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard-server
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: wg-server
          image: wg-server
          securityContext:
            # wireguard requires net admin capabilities to setup VPN
            capabilities:
              add:
                - "NET_ADMIN"
          volumeMounts:
            - mountPath: "/etc/wireguard"
              name: wg-config
            # wireguard needs /dev/net/tun to create VPN tunnel
            - name: dev-net-tun
              mountPath: /dev/net/tun
          # readiness / liveness probe by probing wireguard 51820 UDP port with netcat
          # https://serverfault.com/questions/416205/testing-udp-port-connectivity
          readinessProbe:
            initialDelaySeconds: 10
            failureThreshold: 1
            exec:
              command:
                - "nc"
                - "-vzu"
                - "localhost"
                - "51820"
          livenessProbe:
            initialDelaySeconds: 10
            failureThreshold: 3
            exec:
              command:
                - "nc"
                - "-vzu"
                - "localhost"
                - "51820"
      volumes:
        - name: wg-config
          secret:
            secretName: wg0-config
        - name: dev-net-tun
          hostPath:
            type: 'CharDevice'
            path: /dev/net/tun
