apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: elastic-filerealm
  namespace: elastic-system
spec:
  encryptedData:
    users: AgAvOyIZEi7WdWmA3nfcBZ0CXVsXv9tnJ7reQnylK3+eXrzDkXWdlD2aEOD9ODe7US5WRm1wDVN5zgi7OcF06cDiX02zoTmkn6X/Ad6FisNvfQ9BBkxedEt7r1zr4qtAofULOFyZi23WwB7VphYl2tJXGcgIWXYB8+9lmg3vwPXoTwefL2UxpegOg0c7C2jBMU2uK6EAhMM1mqH0XYPCsAV72j+s+Y5964WQWv3osi2unQTZ9+yBQXyvCNFVI7dRMwC2wtcuZh3VdVL8zJPt/Q9O60AJ37ohS0H360m9F2U/nSsxgYwi9ClGPfea2RlDo48MGKBHxNLJfbQ2MhRiHGlZ0GIGqYRbHlAHc7Y3OQqsCezrww2UOWIvcSZFxCCd5LOQNzxb7Tv3FMjnrcT4pqbUcJj8iWseAEwBcO2rLJyZATQMTZbvYlAKjSjvnV2pSBUJ6ZyZElNszlVZbeWCewAYGdmFIXodB1suA+dcMRBOhvSoSMxbZEeRn6Y7SJ8NPra0ZmwJ0n6yedmcf26YkXjdvXJ5SZJRg+KmMtcMsYFoJgtG8xniW9YMb8KlXRfDpwqkVZ+rvlbq1+1sSHAUhMWm9m1ZPGMYNcm78YRd3j6H92bfHgP9CeZ35cnZuaG0n/KltSgw5y2NsyjFz3xTbR+C0/5gm9XNRpkJ8ym1lbdKNVYNPCTvXWBnbCDM1Ng+V44wNMPnJ2kAwVhClAj9bRPn3qeqwjYMc+jFCMZgV2aaFK93aS7Ddf3FLrgC+s4xrD9H0PJFdluciNt8FHdan6J6GocgKTkV7Q4DqNw=
    users_roles: AgDWBPonUqakcisaMB/Z8Tksabb7fIy87h9Ny2Q5MNNs9gyK4U7DH/X1is3oUaaSOMxIOZkkZbkmq7x10G2SbxNW3QkOJq3n/X5BEVgPCIlylILvhRO6zhdCSRK2uPdnLZOpCUodoZcD5SOmIrr6KLgWNHfM15y1w8s7osQcTpV5XgCj+bw4c+Vbknupc9cJ8KWtdW8SRTT32U9wZYsJp4ltf0XHAFjCtl72Bk6MKylGn66qoMvVFv7K53CwrRLaNgpZmuUYHLfHSvuR+e6ByndAAuCYonocIuzDYYRqdjTRxwAsDKDWKFmKrL1BX6KovdtPmuaCHEu811eeocpqUSnHWzNR4Dw0sVFIH3iFzgxS45AM0MdvRJV/Wintb9dZyGrqpxUytIBaiHQ6IRpyuRShOzcevaPVeoDkTTr0rAZDNawbS8pAJuMXCj8r4F538zJWWH7Dnhf4m/r5P8EaXJdcjlE0jxgBUpYNWq+8IVkdNYfwmshflE9L9cuqJbqiFuMPSUXhpNrbzD2TT5c1FJbaSC9Kwo9dUu+HgaIfVHXeCniaT9GhbWIxRCqN4trlD5vrsrs0PpmXI1eREj89Y081Uid7ARryEi+K7CAHQP7re8w9kOuFjXr/9Q03WnZVEx7NbicM6m9ZnqL0MLKqh+bb5WVuW4nCd75vPnghs6CQS3WDVvWFURzZPwUbck6h788MK1SNW851jfmjokHlSqzi4BJjbh8WMJ8=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: elastic-filerealm
      namespace: elastic-system
