#
# nimbus
# kibana visualization
#

apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 7.13.3
  count: 1
  elasticsearchRef:
    name: elasticsearch
    namespace: logging
