#
# nimbus
# elastic cloud operator kustomization
#

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# deploy elastic cloud operator to deploy elastic cloud components via CRDs
- https://download.elastic.co/downloads/eck/1.6.0/all-in-one.yaml
# deploy a single node elasticsearch cluster with kibana for visualization
- elasticsearch.yaml
- kibana.yaml

namespace: elastic-system
commonLabels:
  part-of: elastic-cloud
