#
# nimbus
# argocd app to deploy cert-manager
#

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mrzzy/nimbus.git
    targetRevision: HEAD
    path: k8s/kustomize/cert-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
