#
# nimbus
# argocd app to deploy elastic cloud components
#

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic-cloud
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mrzzy/nimbus.git
    targetRevision: HEAD
    path: k8s/kustomize/elastic-cloud
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  # ignore changes to the CA bundle which seems to be automatically rewritten
  # causing app to go out of sync from ArgoCD's perspective.
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    jsonPointers:
      - /webhooks/0/clientConfig/caBundle
      - /webhooks/1/clientConfig/caBundle
      - /webhooks/2/clientConfig/caBundle
      - /webhooks/3/clientConfig/caBundle
      - /webhooks/4/clientConfig/caBundle
      - /webhooks/5/clientConfig/caBundle
      - /webhooks/6/clientConfig/caBundle
      - /webhooks/7/clientConfig/caBundle
      - /webhooks/8/clientConfig/caBundle
      - /webhooks/9/clientConfig/caBundle
      - /webhooks/10/clientConfig/caBundle
