#
# nimbus
# secrets registering public helm chart repository with ArgoCD
#

apiVersion: v1
kind: Secret
metadata:
  name: argocd-bitnami-helm-repo
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: bitnami
  url: https://charts.bitnami.com/bitnami
  type: helm
