apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: konnectivity-agent-autoscaler
  namespace: kube-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      k8s-app: konnectivity-agent-autoscaler
