#
# Nimbus
# K8s Deployment
#

apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  # Nginx Ingress Controller
  # Ingress: Nginx
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.3.0/deploy/static/provider/cloud/deploy.yaml
  # Authentication: oauth2-proxy
  - ./auth
  # Media Server: Jellyfin & Rtorrent
  - ./media
  # CSI Rclone: S3-like cloud storage backed Persistent Volumes
  - ./csi-rclone
  # Monitoring: Prometheus, Grafana
  - ./monitoring
  # EBook Library: Calibre Web
  - ./library
  # Data Pipelines: Airflow
  - ./pipeline
