#
# Nimbus
# K8s Deployment
# Base Deployment
#

apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  # Nginx Ingress Controller
  # Ingress: Nginx
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.3.0/deploy/static/provider/cloud/deploy.yaml
  # Storage: PostgreSQL
  - ./storage
  # Authentication: oauth2-proxy
  - ./auth
  # Media Server: Jellyfin & Rtorrent
  - ./media
  # CSI Rclone: S3-like cloud storage backed Persistent Volumes
  - ./csi-rclone
  # Monitoring: Prometheus, Grafana
  - ./monitoring
  # EBook Library: Calibre Web
  - ./library
  # Data Pipelines: Apache Airflow
  - ./pipeline
  # Analytics & Visualisation: Apache Superset
  - ./analytics
# patch all jobs with ttl 0 to be automatically cleaned up upon completion
patches:
  - path: ./patches/patch-job-ttl.yaml
    target:
      group: batch
      version: v1
      kind: Job
