#
# Nimbus
# K8s Deployment
# LKE overlay
#

apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - ../base
  - ./ingress

patches:
  - path: media/patch-pv.yaml
  - path: library/patch-pv.yaml

patchesJson6902:
  # patch Metrics Server to disable TLS when scraping Linode worker's kubelet as
  # Linode does not configure with the correct TLS certificate.
  # https://github.com/kubernetes-sigs/metrics-server/issues/1025
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: metrics-server
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-1
        value: --kubelet-insecure-tls
