#
# Nimbus
# K8s Deployment
# LKE overlay
#

apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - ../base
  - ./media/ingress

secretGenerator:
  # patch oauth2 proxy secret with actual secret values
  - name: login-oauth2-proxy
    behavior: replace
    # unset env vars in env file will be read from the execution environment
    # https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/#configmapgenerator
    env: oauth2-proxy/secret.env

configMapGenerator:
  - name: login-oauth2-proxy
    behavior: merge
    files:
      - oauth2-proxy/oauth2_proxy.cfg
  - name: login-oauth2-proxy-accesslist
    files:
      - restricted_user_access=oauth2-proxy/authenticated_emails_file

patches:
  - media/patch-pv.yaml
  - oauth2-proxy/patch-deployment.yaml
  - oauth2-proxy/patch-ingress.yaml
