#
# Nimbus
# K8s Deployment
# Storage
#

apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - namespace.yaml
helmCharts:
  # PostgreSQL: OLTP SQL database
  - name: postgresql
    repo: https://charts.bitnami.com/bitnami
    releaseName: storage
    valuesInline:
      # postgres admin credentials
      auth:
        existingSecret: postgresql-admin
      # initdb: setup users & databases
      primary:
        initdb:
          scriptsSecret: postgresql-initdbq

commonLabels:
  app.kubernetes.io/part-of: storage
  app.kubernetes.io/created-by: kustomize
