#
# Nimbus
# Terraform: Google Cloud Platform
# Deploy Pipeline
#

name: "Deploy Terraform on Google Cloud Platform"
on:
  workflow_dispatch:
    inputs:
      deploy_warp_vm:
        type: boolean
        description: "Deploy WARP VM"
        required: true
jobs:
  apply-terraform-gcp:
    name: "Apply Terraform development on GCP"
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: terraform/gcp
    steps:
      - uses: actions/checkout@v2
      - name: "Setup Terraform CLI"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.9
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: "Terraform Fmt Check"
        run: terraform fmt -check
      - name: "Terraform Init"
        run: terraform init
      - name: "Terraform Validate"
        run: terraform validate -no-color
      - name: "Terraform Plan"
        run: terraform plan
      - name: "Terraform Apply"
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          TF_VAR_has_warp_vm: "${{ github.event.inputs.deploy_warp_vm }}"
        run: terraform apply -auto-approve
