#
# Nimbus
# CI
# Apply k8s manifests
#

name: "Apply K8s Manifests"
on:
  push:
    branches: [main]
jobs:
  apply-k8s:
    name: "Apply K8s Manifests"
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: k8s
    steps:
      - uses: actions/checkout@v3
      - name: "Setup kubectl access to GKE"
        uses: ./.github/actions/setup-gke
        with:
          github_odic_request_token: "${{ env.ACTIONS_ID_TOKEN_REQUEST_TOKEN }}"
          github_odic_request_url: "${{ env.ACTIONS_ID_TOKEN_REQUEST_URL }}"
      - name: "Apply current K8s manifests to GKE"
        env:
          OAUTH2_PROXY_CLIENT_ID: "${{ secrets.K8S_OAUTH2_PROXY_CLIENT_ID }}"
          OAUTH2_PROXY_CLIENT_SECRET: "${{ secrets.K8S_OAUTH2_PROXY_CLIENT_SECRET }}"
          OAUTH2_PROXY_COOKIE_SECRET: "${{ secrets.K8S_OAUTH2_PROXY_COOKIE_SECRET }}"
        run: >
          kubectl kustomize --enable-helm ./base |
          kubectl apply --server-side --force-conflicts -f -
