#
# Nimbus
# CI
# Apply k8s manifests
#

name: "Apply K8s Manifests"
on:
  push:
    branches: [main]
permissions:
  # needed for actions/checkout to clone repo
  contents: read
  # allow odic token to be issued for auth via GCP's workload identity pool
  id-token: write
jobs:
  apply-k8s:
    name: "Apply K8s Manifests"
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: k8s
    steps:
      - uses: actions/checkout@v3
      - name: "Setup kubectl access to GKE"
        uses: ./.github/actions/setup-gke
      - name: "Template K8s secret .env files"
        working-directory: . # project root
        env:
          K8S_OAUTH2_PROXY_CLIENT_ID: "${{ secrets.K8S_OAUTH2_PROXY_CLIENT_ID }}"
          K8S_OAUTH2_PROXY_CLIENT_SECRET: "${{ secrets.K8S_OAUTH2_PROXY_CLIENT_SECRET }}"
          K8S_OAUTH2_PROXY_COOKIE_SECRET: "${{ secrets.K8S_OAUTH2_PROXY_COOKIE_SECRET }}"
          K8S_STORAGE_POSTGRESQL_PASSWORD: "${{ secrets.K8S_STORAGE_POSTGRESQL_PASSWORD }}"
          K8S_AIRFLOW_POSTGRESQL_PASSWORD: "${{ secrets.K8S_AIRFLOW_POSTGRESQL_PASSWORD }}"
          K8S_AIRFLOW_WEBSERVER_KEY: "${{ secrets.K8S_AIRFLOW_WEBSERVER_KEY }}"
          K8S_AIRFLOW_CONN_AWS_DEFAULT: "${{ secrets.K8S_AIRFLOW_CONN_AWS_DEFAULT }}"
          K8S_AIRFLOW_CONN_REDSHIFT_DEFAULT: "${{ secrets.K8S_AIRFLOW_CONN_REDSHIFT_DEFAULT }}"
          K8S_AIRFLOW_CONN_PVD_SIMPLYGO_SRC: "${{ secrets.K8S_AIRFLOW_CONN_PVD_SIMPLYGO_SRC }}"
          K8S_AIRFLOW_CONN_YNAB_API: "${{ secrets.K8S_AIRFLOW_CONN_YNAB_API }}"
          K8S_AIRFLOW__SMTP__SMTP_USER: "${{ secrets.K8S_AIRFLOW__SMTP__SMTP_USER }}"
          K8S_AIRFLOW__SMTP__SMTP_PASSWORD: "${{ secrets.K8S_AIRFLOW__SMTP__SMTP_PASSWORD }}"
          K8S_SUPERSET_POSTGRESQL_PASSWORD: "${{ secrets.K8S_SUPERSET_POSTGRESQL_PASSWORD }}"
          K8S_SUPERSET_SECRET_KEY: "${{ secrets.K8S_SUPERSET_SECRET_KEY }}"
        run: make k8s-secrets
      - name: "Apply current K8s manifests to GKE"
        run: >
          kubectl kustomize --enable-helm ./base |
          kubectl apply --server-side --force-conflicts -f -
