#
# Nimbus
# Terraform
# Cleanup Costly Resources
#

name: "Cleanup Costly Resources"
on:
  # UTC 1500 - 11pm in SGT
  schedule: [ cron: "00 15 * * *" ]
jobs:
  cleanup-terraform:
    name: "Apply lean Terraform deployment"
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: terraform
    steps:
      - uses: actions/checkout@v2
      - name: "Setup Terraform CLI"
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.3
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: "Terraform Init"
        run: terraform init
      - name: "Terraform Apply"
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          TF_VAR_has_warp_vm: false
        run: terraform apply -auto-approve
