#
# nimbus
# Docker Container CI Pipeline
#

name: "Build & Push Docker Containers to GCP"
on:
  push: {}
env:
  GCP_REGION: asia-southeast1
  GCP_PROJECT: mrzzy-sandbox
  GCP_REPO: nimbus
permissions:
  # needed for actions/checkout to clone repo
  contents: read
  # allow odic token to be issued for auth via GCP's workload identity pool
  id-token: write
jobs:
  proxy-gae:
    name: "Build & Push proxy-gae Docker container"
    defaults:
      run:
        working-directory: docker/proxy-gae
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v3
      - name: "Lint Dockerfile with Hadolint"
        run: docker run --rm -i ghcr.io/hadolint/hadolint < Dockerfile
      - name: "Build Container"
        run: |
          CONTAINER="${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT}/${GCP_REPO}/proxy-gae"
          echo "CONTAINER=${CONTAINER}" >>$GITHUB_ENV
          docker build -t $CONTAINER .
      - id: 'auth'
        name: "Authenticate to GCP with Workload Identity Federation"
        uses: google-github-actions/auth@v0.8.3
        with:
          workload_identity_provider: "projects/652407106283/locations/global/workloadIdentityPools/gh-actions-mrzzy-nimbus/providers/gh-oidc-provider-mrzzy-nimbus"
          service_account: "gh-actions-mrzzy-nimbus@mrzzy-sandbox.iam.gserviceaccount.com"
      - name: "Setup gcloud"
        uses: 'google-github-actions/setup-gcloud@v0.6.2'
      - name: "Setup docker push credentials"
        run: |
          gcloud auth configure-docker asia-southeast1-docker.pkg.dev
      - name: "Push container to GCP Artifact Repository"
        # only enable push on main branch
        if: ${{ github.ref == 'refs/heads/main' }}
        run: docker push $CONTAINER
