#
# nimbus
# Docker Container CI Pipeline
#

name: "Build & Push Docker Containers to GCP"
on:
  push: {}
env:
  GCP_REGION: asia-southeast1
  GCP_PROJECT: mrzzy-sandbox
  GCP_REPO: nimbus
permissions:
  # needed for actions/checkout to clone repo
  contents: read
  # allow odic token to be issued for auth via GCP's workload identity pool
  id-token: write
jobs:
  proxy-gae:
    name: "Build & Push proxy-gae Docker container"
    defaults:
      run:
        working-directory: docker/proxy-gae
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v3
      - name: "Lint Dockerfile with Hadolint"
        run: docker run --rm -i ghcr.io/hadolint/hadolint < Dockerfile
      - name: "Build Container"
        run: |
          CONTAINER="${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT}/${GCP_REPO}/proxy-gae"
          echo "CONTAINER=${CONTAINER}" >>$GITHUB_ENV
          docker build -t $CONTAINER .
      - name: "Authenticate to GCP with Workload Identity Federation"
        uses: google-github-actions/auth@v0.8.1
        with:
          workload_identity_provider: "projects/652407106283/locations/global/workloadIdentityPools/gh-actions-mrzzy-nimbus/providers/gh-oidc-provider-mrzzy-nimbus"
          service_account: "gh-actions-mrzzy-nimbus@mrzzy-sandbox.iam.gserviceaccount.com"
      - name: "Configure GCP docker credential helper"
        run: |
          # install docker credential helper
          set -exu -o pipefail
          VERSION=2.1.6
          curl -fsSL "https://github.com/GoogleCloudPlatform/docker-credential-gcr/releases/download/v${VERSION}/docker-credential-gcr_linux_amd64-${VERSION}.tar.gz" \
            | tar xz docker-credential-gcr \
            && chmod +x docker-credential-gcr && sudo mv docker-credential-gcr /usr/local/bin
          # configure docker credentials
          docker-credential-gcr configure-docker --registries=${GCP_REGION}-docker.pkg.dev
          echo "https://${GCP_REGION}-docker.pkg.dev" | docker-credential-gcr get >/dev/null
      - name: "Push container to GCP Artifact Repository"
        run: docker push $CONTAINER
