#
# Nimbus
# CI
# Docker
#

name: Build and Publish Docker Containers
on: push
jobs:
  publish-container:
    name: "${{ matrix.container }}: Build & Publish Docker Container"
    strategy:
      fail-fast: false
      matrix:
        container:
          - naiveproxy
    runs-on: ubuntu-22.04
    # add permissions needed to push containers to GHCR with GITHUB_TOKEN
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Log in to the GitHub Container registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"
      - id: docker-metadata
        name: "Gather metadata for tagging / labeling ${{ matrix.source }} Container"
        uses: docker/metadata-action@v4.6.0
        with:
          images: "ghcr.io/${{ github.repository_owner }}/${{ matrix.container }}"
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=semver,pattern={{version}}
            # set latest tag for default branch (main)
            type=raw,value=latest,enable={{is_default_branch}}
      - name: "Build and Push ${{ matrix.container }} Container to GitHub Container Registry"
        uses: docker/build-push-action@v4.1.1
        with:
          context: "docker/${{ matrix.container }}"
          tags: ${{ steps.docker-metadata.outputs.tags }}
          labels: ${{ steps.docker-metadata.outputs.labels }}
          push: true
