#
# Nimbus
# Terraform
# Lint Terraform Pipeline
#

name: "Lint & Plan Terraform"
on: push
jobs:
  lint-terraform:
    name: "Lint Terraform deployment"
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: terraform
    steps:
      - uses: actions/checkout@v3
      - name: "Setup Terraform CLI"
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.2
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: "Terraform Fmt Check"
        run: terraform fmt -check
      - name: "Terraform Init"
        run: terraform init
      - name: "Terraform Validate"
        run: terraform validate -no-color

  plan-terraform:
    name: "Plan Terraform deployment"
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: terraform
    steps:
      - uses: actions/checkout@v3
      - name: "Setup Terraform CLI"
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.2
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: "Terraform Init"
        run: terraform init
      - name: "Terraform Plan"
        run:
          terraform plan
