#
# Nimbus
# CI
# Lint K8s Workflow
#

name: "Lint & Diff K8s Manifests"
on: push
jobs:
  dry-run-k8s:
    env:
      KUBECTL_FLAGS: "--server-side --force-conflicts"
    name: "Dry Run K8s Manifests"
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: k8s
    steps:
      - uses: actions/checkout@v3
      - name: "Setup kubectl access to GKE"
        uses: ./.github/actions/setup-gke
        with:
          github_odic_request_token: "${{ env.ACTIONS_ID_TOKEN_REQUEST_TOKEN }}"
          github_odic_request_url: "${{ env.ACTIONS_ID_TOKEN_REQUEST_URL }}"
      - name: "Perform server-side Dry Run of K8s manifests"
        env:
          OAUTH2_PROXY_CLIENT_ID: "${{ secrets.K8S_OAUTH2_PROXY_CLIENT_ID }}"
          OAUTH2_PROXY_CLIENT_SECRET: "${{ secrets.K8S_OAUTH2_PROXY_CLIENT_SECRET }}"
          OAUTH2_PROXY_COOKIE_SECRET: "${{ secrets.K8S_OAUTH2_PROXY_COOKIE_SECRET }}"
        run: >
          kubectl kustomize --enable-helm ./base |
          kubectl apply ${KUBECTL_FLAGS} --dry-run=server -f -

      - name: "Diff K8s manifests with current K8s Cluster's configuration"
        env:
          OAUTH2_PROXY_CLIENT_ID: "${{ secrets.K8S_OAUTH2_PROXY_CLIENT_ID }}"
          OAUTH2_PROXY_CLIENT_SECRET: "${{ secrets.K8S_OAUTH2_PROXY_CLIENT_SECRET }}"
          OAUTH2_PROXY_COOKIE_SECRET: "${{ secrets.K8S_OAUTH2_PROXY_COOKIE_SECRET }}"
        run: |
          # kubectl diff returns status code = 1 when changes are detected,
          # >1 if an actual error occurs
          kubectl kustomize --enable-helm ./base | \
            kubectl diff ${KUBECTL_FLAGS} -f - || EXIT_CODE=$?
          test ${EXIT_CODE:-1} -eq 1
