#
# Nimbus
# CI
# Lint K8s Workflow
#

name: "Lint & Diff K8s Manifests"
on: push
permissions:
  # needed for actions/checkout to clone repo
  contents: read
  # allow odic token to be issued for auth via GCP's workload identity pool
  id-token: write
jobs:
  dry-run-k8s:
    env:
      KUBECTL_FLAGS: "--server-side --force-conflicts"
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: k8s
    steps:
      - uses: actions/checkout@v3
      - name: "Setup kubectl access to GKE"
        uses: ./.github/actions/setup-gke
      - name: "Template K8s secret .env files"
        working-directory: . # project root
        env:
          K8S_OAUTH2_PROXY_CLIENT_ID: "${{ secrets.K8S_OAUTH2_PROXY_CLIENT_ID }}"
          K8S_OAUTH2_PROXY_CLIENT_SECRET: "${{ secrets.K8S_OAUTH2_PROXY_CLIENT_SECRET }}"
          K8S_OAUTH2_PROXY_COOKIE_SECRET: "${{ secrets.K8S_OAUTH2_PROXY_COOKIE_SECRET }}"
          K8S_STORAGE_POSTGRESQL_PASSWORD: "${{ secrets.K8S_STORAGE_POSTGRESQL_PASSWORD }}"
          K8S_AIRFLOW_POSTGRESQL_PASSWORD: "${{ secrets.K8S_AIRFLOW_POSTGRESQL_PASSWORD }}"
          K8S_AIRFLOW_WEBSERVER_KEY: "${{ secrets.K8S_AIRFLOW_WEBSERVER_KEY }}"
          K8S_AIRFLOW_CONN_AWS_DEFAULT: "${{ secrets.K8S_AIRFLOW_CONN_AWS_DEFAULT }}"
          K8S_AIRFLOW_CONN_REDSHIFT_DEFAULT: "${{ secrets.K8S_AIRFLOW_CONN_REDSHIFT_DEFAULT }}"
          K8S_AIRFLOW_CONN_PVD_SIMPLYGO_SRC: "${{ secrets.K8S_AIRFLOW_CONN_PVD_SIMPLYGO_SRC }}"
          K8S_AIRFLOW_CONN_YNAB_API: "${{ secrets.K8S_AIRFLOW_CONN_YNAB_API }}"
          K8S_AIRFLOW__SMTP__SMTP_USER: "${{ secrets.K8S_AIRFLOW__SMTP__SMTP_USER }}"
          K8S_AIRFLOW__SMTP__SMTP_PASSWORD: "${{ secrets.K8S_AIRFLOW__SMTP__SMTP_PASSWORD }}"
          K8S_SUPERSET_POSTGRESQL_PASSWORD: "${{ secrets.K8S_SUPERSET_POSTGRESQL_PASSWORD }}"
          K8S_SUPERSET_SECRET_KEY: "${{ secrets.K8S_SUPERSET_SECRET_KEY }}"
          K8S_SS_SERVER_PASSWORD: "${{ secrets.K8S_SS_SERVER_PASSWORD }}"
          K8S_NAIVEPROXY_USERNAME: "${{ secrets.K8S_NAIVEPROXY_USERNAME }}"
          K8S_NAIVEPROXY_PASSWORD: "${{ secrets.K8S_NAIVEPROXY_PASSWORD }}"
        run: make k8s-secrets
      - name: "Perform server-side Dry Run of K8s manifests"
        run: >
          kubectl kustomize --enable-helm ./gcp |
          kubectl apply ${KUBECTL_FLAGS} --dry-run=server -f -
      - name: "Diff K8s manifests with current K8s Cluster's configuration"
        run: |
          # kubectl diff returns status code = 1 when changes are detected,
          # >1 if an actual error occurs
          kubectl kustomize --enable-helm ./gcp | \
            kubectl diff ${KUBECTL_FLAGS} -f - || EXIT_CODE=$?
          test ${EXIT_CODE:-1} -eq 1
