#
# Nimbus
# CI
# Rotate Proxy IPs
#

name: "Rotate Proxy IPs"
on:
  # UTC 1800 - 2am in SGT
  schedule: [ cron: "00 18 * * *" ]
  # manual trigger
  workflow_dispatch: {}
permissions:
  # needed for actions/checkout to clone repo
  contents: read
  # allow odic token to be issued for auth via GCP's workload identity pool
  id-token: write
jobs:
  rotate-ips:
    strategy:
      fail-fast: false
      matrix:
        proxy:
          - shadowsocks
          - naiveproxy
    name: "${{ matrix.proxy }}: Rotate Proxy IP"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: "Setup kubectl access to GKE"
        uses: ./.github/actions/setup-gke
      - name: "Setup Terraform CLI"
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.2
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: "Rotate Proxy IP"
        uses: ./.github/actions/rotate-ip
        with:
          namespace: proxy
          name: "${{ matrix.proxy }}"
          dns_record: 'module.dns.cloudflare_record.route["${{ matrix.proxy }}"]'
