#
# nimbus
# terraform linode cloud
# continuous integration pipeline
#

name: "CI/Terraform: Linode Cloud"
on:
  push:
    paths:
      - "terraform/linode/**"
jobs:
  terraform-lint-plan:
    name: "Terraform Lint & Plan: Linode Cloud"
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: "terraform/linode"
    steps:
      - uses: actions/checkout@v2
      - name: "Setup Terraform CLI"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.1
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: "Terraform Fmt Check"
        run: terraform fmt -check
      - name: "Terraform Init"
        run: terraform init
      - name: "Terraform Validate"
        run: terraform validate -no-color
      - name: "Terraform Plan"
        run: terraform plan
