#
# nimbus
# Argo Workflows
# RBAC Role Bindinng
#

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-workflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workflow
subjects:
- kind: ServiceAccount
  name: default
